name = OpenPublic Content Translation
description = Enable content translation
machine_name = openpublic_translation_content
version = 1.0
downloadable = openpublic_translation_content 1.0
author = Phase2 Technology
author_url = http://www.phase2technology.com/
logo = logo.png
screenshots[] = screenshot.jpg
downloadables[openpublic_translation_content 1.0] = https://github.com/phase2/openpublic_translation_content/tarball/master